version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: cesped_development
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  app:
    build: .
    command: "bundle exec rails s -b 0.0.0.0"
    env_file: .env
    volumes:
      - .:/app/cesped
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    environment:
      DB_HOST: db

volumes:
  bundle:
